---
deployment:
  tasks:
    # Update composer dependencies
    - export DEPLOYPATH=/home/wp-boilerplate/public_html
    - /bin/cp composer.* ${DEPLOYPATH}
    - composer --working-dir=${DEPLOYPATH} install
    # Kaliroots-based theme
    #- export THEME=wp-boilerplate
    - '[ -z "$THEME2" ] || { yarn --cwd ./wp-content/themes/${THEME} install; }'
    - '[ -z "$THEME2" ] || { yarn --cwd ./wp-content/themes/${THEME} build; }'
    # Version-controlled plugins / themes
    - rsync -av ./wp-content/ ${DEPLOYPATH}/wp-content/ --exclude=`git -C . ls-files --exclude-standard -oi --directory` --exclude=node_modules --dry-run
